/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "pwmxkcijsrykjvxnzxnt"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3bXhrY2lqc3J5a2p2eG56eG50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzODE4ODQsImV4cCI6MjA3Mzk1Nzg4NH0._uLL-cO-1UI8uT-dnnWrlUajthYkWl1iMvYPHFfFYmI"